crossplane:

  provider:
    # -- A list of Provider packages to install.
    packages: []
  
  configuration:
    # -- A list of Configuration packages to install.
    packages: []
  
  function:
    # -- A list of Function packages to install
    packages: 
    - xpkg.upbound.io/crossplane-contrib/function-kcl:v0.2.0
