apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: amine.kawani@outlook.com
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-staging
    server: 'https://acme-staging-v02.api.letsencrypt.org/directory'
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik