apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials-cp
  namespace: crossplane
  labels:
    type: provider-credentials
type: Opaque
stringData:
  credentials: |
    {
      "client_id":"crossplane",
      "client_secret":"demosecret",
      "url":"http://keycloak-service.keycloak.svc.cluster.local:8080",
      "realm":"master",
      "base_Path":"/"
    }
---
