---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-client-{{ .Values.deployments.keycloak.vaultclient.config.clientID }}-password"
type: Opaque
stringData:
  {{ .Values.deployments.keycloak.vaultclient.config.clientID }}: {{ .Values.deployments.keycloak.vaultclient.config.clientSecret }}

---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  deletionPolicy: Delete
  forProvider:
    accessType: CONFIDENTIAL 
    clientId: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
    name: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
    realmId: {{ .Values.deployments.keycloak.realm.realmid }}
    adminUrl: "https://vault{{ .Values.deployments.ingress.fqdn }}"
    rootUrl: "https://vault{{ .Values.deployments.ingress.fqdn }}"
    directAccessGrantsEnabled: false
    standardFlowEnabled: true
    serviceAccountsEnabled: true
#    managementPolicies: ["Observe"]
    validRedirectUris:
      - "https://vault{{ .Values.deployments.ingress.fqdn }}/ui/vault/auth/oidc/oidc/callback"
    clientSecretSecretRef:
      key: {{ .Values.deployments.keycloak.vaultclient.config.clientID }}
      name: "{{ .Release.Name }}-client-{{ .Values.deployments.keycloak.vaultclient.config.clientID }}-password"
      namespace: {{ .Release.Namespace }}
    loginTheme: keycloak
  providerConfigRef:
    name: "{{ .Release.Name }}-config"
