apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.pvc.name }}"
  labels:
    app: "{{ .Values.deployments.postgres.service.name }}"
spec:
  #storageClassName: "default"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.pvc.size }}"
