{{- range .Values.teams }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-app-of-apps
  namespace: adn-{{ .name }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: adn-{{ .name }}
    server: https://kubernetes.default.svc
  project: {{ .name }}-project
  sources:
  - path:  {{ .appOfAppsRepo.path }}
    repoURL: {{ .appOfAppsRepo.repoURL }}
    targetRevision:  {{ .appOfAppsRepo.revision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
